// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: alerts.sql

package db

import (
	"context"
	"database/sql"
)

const cancelAlert = `-- name: CancelAlert :exec
UPDATE alerts SET status = 'cancelled', next_attempt_at = NULL, last_error = ? WHERE id = ? AND status = 'pending'
`

type CancelAlertParams struct {
	LastError string
	ID        string
}

func (q *Queries) CancelAlert(ctx context.Context, arg CancelAlertParams) error {
	_, err := q.db.ExecContext(ctx, cancelAlert, arg.LastError, arg.ID)
	return err
}

const claimAlert = `-- name: ClaimAlert :execrows
UPDATE alerts SET attempts = attempts + 1, last_attempt_at = ?1, next_attempt_at = ?2
WHERE id = ?3 AND status = 'pending' AND next_attempt_at <= ?1
`

type ClaimAlertParams struct {
	Now        sql.NullString
	LeaseUntil sql.NullString
	ID         string
}

// Takes a due alert for one attempt. next_attempt_at becomes a lease, so
// another process does not attempt it too, and an attempt cut short by a
// crash is retried once the lease runs out.
func (q *Queries) ClaimAlert(ctx context.Context, arg ClaimAlertParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, claimAlert, arg.Now, arg.LeaseUntil, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const countUndeliveredAlerts = `-- name: CountUndeliveredAlerts :many
SELECT job_id, count(*) AS alerts FROM alerts
WHERE status = 'undelivered' OR (status = 'pending' AND last_error != '')
GROUP BY job_id
`

type CountUndeliveredAlertsRow struct {
	JobID  string
	Alerts int64
}

// Alerts that failed at least once and are not yet delivered, by job.
func (q *Queries) CountUndeliveredAlerts(ctx context.Context) ([]CountUndeliveredAlertsRow, error) {
	rows, err := q.db.QueryContext(ctx, countUndeliveredAlerts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountUndeliveredAlertsRow
	for rows.Next() {
		var i CountUndeliveredAlertsRow
		if err := rows.Scan(&i.JobID, &i.Alerts); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteAlertsBefore = `-- name: DeleteAlertsBefore :execrows
DELETE FROM alerts WHERE created_at < ? AND status != 'pending'
`

func (q *Queries) DeleteAlertsBefore(ctx context.Context, createdAt string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteAlertsBefore, createdAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const finishAlertAttempt = `-- name: FinishAlertAttempt :exec
UPDATE alerts SET status = ?, next_attempt_at = ?, last_error = ?, last_output = ? WHERE id = ?
`

type FinishAlertAttemptParams struct {
	Status        string
	NextAttemptAt sql.NullString
	LastError     string
	LastOutput    string
	ID            string
}

func (q *Queries) FinishAlertAttempt(ctx context.Context, arg FinishAlertAttemptParams) error {
	_, err := q.db.ExecContext(ctx, finishAlertAttempt,
		arg.Status,
		arg.NextAttemptAt,
		arg.LastError,
		arg.LastOutput,
		arg.ID,
	)
	return err
}

const insertAlert = `-- name: InsertAlert :exec
INSERT INTO alerts (id, job_id, run_id, event, hook, environ, created_at, next_attempt_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertAlertParams struct {
	ID            string
	JobID         string
	RunID         sql.NullString
	Event         string
	Hook          string
	Environ       string
	CreatedAt     string
	NextAttemptAt sql.NullString
}

func (q *Queries) InsertAlert(ctx context.Context, arg InsertAlertParams) error {
	_, err := q.db.ExecContext(ctx, insertAlert,
		arg.ID,
		arg.JobID,
		arg.RunID,
		arg.Event,
		arg.Hook,
		arg.Environ,
		arg.CreatedAt,
		arg.NextAttemptAt,
	)
	return err
}

const listJobAlerts = `-- name: ListJobAlerts :many
SELECT id, job_id, run_id, event, hook, environ, created_at, status, attempts, next_attempt_at, last_attempt_at, last_error, last_output FROM alerts WHERE job_id = ? ORDER BY created_at DESC, rowid DESC LIMIT ?
`

type ListJobAlertsParams struct {
	JobID string
	Limit int64
}

func (q *Queries) ListJobAlerts(ctx context.Context, arg ListJobAlertsParams) ([]Alert, error) {
	rows, err := q.db.QueryContext(ctx, listJobAlerts, arg.JobID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Alert
	for rows.Next() {
		var i Alert
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.RunID,
			&i.Event,
			&i.Hook,
			&i.Environ,
			&i.CreatedAt,
			&i.Status,
			&i.Attempts,
			&i.NextAttemptAt,
			&i.LastAttemptAt,
			&i.LastError,
			&i.LastOutput,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingAlerts = `-- name: ListPendingAlerts :many
SELECT alerts.id, alerts.job_id, alerts.run_id, alerts.event, alerts.hook, alerts.environ, alerts.created_at, alerts.status, alerts.attempts, alerts.next_attempt_at, alerts.last_attempt_at, alerts.last_error, alerts.last_output, jobs.name AS job_name, jobs.on_failure, jobs.on_recover
FROM alerts JOIN jobs ON jobs.id = alerts.job_id
WHERE alerts.status = 'pending' AND (?1 IS NULL OR alerts.job_id = ?1)
ORDER BY alerts.job_id, alerts.created_at, alerts.rowid
`

type ListPendingAlertsRow struct {
	Alert     Alert
	JobName   string
	OnFailure sql.NullString
	OnRecover sql.NullString
}

// Oldest first within each job, so a job's alerts are delivered in order.
func (q *Queries) ListPendingAlerts(ctx context.Context, jobID interface{}) ([]ListPendingAlertsRow, error) {
	rows, err := q.db.QueryContext(ctx, listPendingAlerts, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPendingAlertsRow
	for rows.Next() {
		var i ListPendingAlertsRow
		if err := rows.Scan(
			&i.Alert.ID,
			&i.Alert.JobID,
			&i.Alert.RunID,
			&i.Alert.Event,
			&i.Alert.Hook,
			&i.Alert.Environ,
			&i.Alert.CreatedAt,
			&i.Alert.Status,
			&i.Alert.Attempts,
			&i.Alert.NextAttemptAt,
			&i.Alert.LastAttemptAt,
			&i.Alert.LastError,
			&i.Alert.LastOutput,
			&i.JobName,
			&i.OnFailure,
			&i.OnRecover,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunAlerts = `-- name: ListRunAlerts :many
SELECT id, job_id, run_id, event, hook, environ, created_at, status, attempts, next_attempt_at, last_attempt_at, last_error, last_output FROM alerts WHERE run_id = ? ORDER BY created_at, rowid
`

func (q *Queries) ListRunAlerts(ctx context.Context, runID sql.NullString) ([]Alert, error) {
	rows, err := q.db.QueryContext(ctx, listRunAlerts, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Alert
	for rows.Next() {
		var i Alert
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.RunID,
			&i.Event,
			&i.Hook,
			&i.Environ,
			&i.CreatedAt,
			&i.Status,
			&i.Attempts,
			&i.NextAttemptAt,
			&i.LastAttemptAt,
			&i.LastError,
			&i.LastOutput,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
