// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: crontab.sql

package db

import (
	"context"
	"database/sql"
)

const deleteCrontabSnapshotsBefore = `-- name: DeleteCrontabSnapshotsBefore :execrows
DELETE FROM crontab_snapshots WHERE crontab_snapshots.taken_at < ?
  AND crontab_snapshots.id != (SELECT newest.id FROM crontab_snapshots AS newest ORDER BY newest.taken_at DESC LIMIT 1)
`

// Keeps the newest snapshot, which later changes are compared with.
func (q *Queries) DeleteCrontabSnapshotsBefore(ctx context.Context, takenAt string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteCrontabSnapshotsBefore, takenAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const insertCrontabChange = `-- name: InsertCrontabChange :exec
INSERT INTO crontab_changes (id, snapshot_id, taken_at, job_slug, kind, before_text, after_text)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type InsertCrontabChangeParams struct {
	ID         string
	SnapshotID string
	TakenAt    string
	JobSlug    sql.NullString
	Kind       string
	BeforeText string
	AfterText  string
}

func (q *Queries) InsertCrontabChange(ctx context.Context, arg InsertCrontabChangeParams) error {
	_, err := q.db.ExecContext(ctx, insertCrontabChange,
		arg.ID,
		arg.SnapshotID,
		arg.TakenAt,
		arg.JobSlug,
		arg.Kind,
		arg.BeforeText,
		arg.AfterText,
	)
	return err
}

const insertCrontabSnapshot = `-- name: InsertCrontabSnapshot :exec
INSERT INTO crontab_snapshots (id, taken_at, content_hash, content) VALUES (?, ?, ?, ?)
`

type InsertCrontabSnapshotParams struct {
	ID          string
	TakenAt     string
	ContentHash string
	Content     string
}

func (q *Queries) InsertCrontabSnapshot(ctx context.Context, arg InsertCrontabSnapshotParams) error {
	_, err := q.db.ExecContext(ctx, insertCrontabSnapshot,
		arg.ID,
		arg.TakenAt,
		arg.ContentHash,
		arg.Content,
	)
	return err
}

const latestCrontabSnapshot = `-- name: LatestCrontabSnapshot :one
SELECT id, taken_at, content_hash, content FROM crontab_snapshots ORDER BY taken_at DESC LIMIT 1
`

func (q *Queries) LatestCrontabSnapshot(ctx context.Context) (CrontabSnapshot, error) {
	row := q.db.QueryRowContext(ctx, latestCrontabSnapshot)
	var i CrontabSnapshot
	err := row.Scan(
		&i.ID,
		&i.TakenAt,
		&i.ContentHash,
		&i.Content,
	)
	return i, err
}

const listCrontabChanges = `-- name: ListCrontabChanges :many
SELECT id, snapshot_id, taken_at, job_slug, kind, before_text, after_text FROM crontab_changes ORDER BY taken_at DESC, rowid LIMIT ?
`

func (q *Queries) ListCrontabChanges(ctx context.Context, limit int64) ([]CrontabChange, error) {
	rows, err := q.db.QueryContext(ctx, listCrontabChanges, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CrontabChange
	for rows.Next() {
		var i CrontabChange
		if err := rows.Scan(
			&i.ID,
			&i.SnapshotID,
			&i.TakenAt,
			&i.JobSlug,
			&i.Kind,
			&i.BeforeText,
			&i.AfterText,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCrontabChangesSince = `-- name: ListCrontabChangesSince :many
SELECT id, snapshot_id, taken_at, job_slug, kind, before_text, after_text FROM crontab_changes WHERE job_slug IS NOT NULL AND taken_at >= ? ORDER BY taken_at
`

func (q *Queries) ListCrontabChangesSince(ctx context.Context, takenAt string) ([]CrontabChange, error) {
	rows, err := q.db.QueryContext(ctx, listCrontabChangesSince, takenAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CrontabChange
	for rows.Next() {
		var i CrontabChange
		if err := rows.Scan(
			&i.ID,
			&i.SnapshotID,
			&i.TakenAt,
			&i.JobSlug,
			&i.Kind,
			&i.BeforeText,
			&i.AfterText,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobCrontabChanges = `-- name: ListJobCrontabChanges :many
SELECT id, snapshot_id, taken_at, job_slug, kind, before_text, after_text FROM crontab_changes WHERE job_slug = ? ORDER BY taken_at DESC, rowid LIMIT ?
`

type ListJobCrontabChangesParams struct {
	JobSlug sql.NullString
	Limit   int64
}

func (q *Queries) ListJobCrontabChanges(ctx context.Context, arg ListJobCrontabChangesParams) ([]CrontabChange, error) {
	rows, err := q.db.QueryContext(ctx, listJobCrontabChanges, arg.JobSlug, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CrontabChange
	for rows.Next() {
		var i CrontabChange
		if err := rows.Scan(
			&i.ID,
			&i.SnapshotID,
			&i.TakenAt,
			&i.JobSlug,
			&i.Kind,
			&i.BeforeText,
			&i.AfterText,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
