// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: environments.sql

package db

import (
	"context"
)

const deleteUnusedEnvironments = `-- name: DeleteUnusedEnvironments :execrows
DELETE FROM environments
WHERE hash NOT IN (SELECT env_hash FROM runs WHERE env_hash IS NOT NULL)
`

func (q *Queries) DeleteUnusedEnvironments(ctx context.Context) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteUnusedEnvironments)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getEnvironment = `-- name: GetEnvironment :one
SELECT data FROM environments WHERE hash = ?
`

func (q *Queries) GetEnvironment(ctx context.Context, hash string) (string, error) {
	row := q.db.QueryRowContext(ctx, getEnvironment, hash)
	var data string
	err := row.Scan(&data)
	return data, err
}

const insertEnvironment = `-- name: InsertEnvironment :exec
INSERT INTO environments (hash, data, created_at) VALUES (?, ?, ?)
ON CONFLICT(hash) DO NOTHING
`

type InsertEnvironmentParams struct {
	Hash      string
	Data      string
	CreatedAt string
}

func (q *Queries) InsertEnvironment(ctx context.Context, arg InsertEnvironmentParams) error {
	_, err := q.db.ExecContext(ctx, insertEnvironment, arg.Hash, arg.Data, arg.CreatedAt)
	return err
}
