// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: hosts.sql

package db

import (
	"context"
	"database/sql"
)

const createHost = `-- name: CreateHost :exec
INSERT INTO hosts (id, name, token_hash, created_at) VALUES (?, ?, ?, ?)
`

type CreateHostParams struct {
	ID        string
	Name      string
	TokenHash string
	CreatedAt string
}

func (q *Queries) CreateHost(ctx context.Context, arg CreateHostParams) error {
	_, err := q.db.ExecContext(ctx, createHost,
		arg.ID,
		arg.Name,
		arg.TokenHash,
		arg.CreatedAt,
	)
	return err
}

const deleteHost = `-- name: DeleteHost :execrows
DELETE FROM hosts WHERE name = ?
`

func (q *Queries) DeleteHost(ctx context.Context, name string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteHost, name)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getHostByName = `-- name: GetHostByName :one
SELECT id, name, token_hash, created_at, reported_at, report FROM hosts WHERE name = ?
`

func (q *Queries) GetHostByName(ctx context.Context, name string) (Host, error) {
	row := q.db.QueryRowContext(ctx, getHostByName, name)
	var i Host
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TokenHash,
		&i.CreatedAt,
		&i.ReportedAt,
		&i.Report,
	)
	return i, err
}

const getHostByTokenHash = `-- name: GetHostByTokenHash :one
SELECT id, name, token_hash, created_at, reported_at, report FROM hosts WHERE token_hash = ?
`

func (q *Queries) GetHostByTokenHash(ctx context.Context, tokenHash string) (Host, error) {
	row := q.db.QueryRowContext(ctx, getHostByTokenHash, tokenHash)
	var i Host
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TokenHash,
		&i.CreatedAt,
		&i.ReportedAt,
		&i.Report,
	)
	return i, err
}

const listHosts = `-- name: ListHosts :many
SELECT id, name, token_hash, created_at, reported_at, report FROM hosts ORDER BY name COLLATE NOCASE
`

func (q *Queries) ListHosts(ctx context.Context) ([]Host, error) {
	rows, err := q.db.QueryContext(ctx, listHosts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Host
	for rows.Next() {
		var i Host
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.TokenHash,
			&i.CreatedAt,
			&i.ReportedAt,
			&i.Report,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveHostReport = `-- name: SaveHostReport :exec
UPDATE hosts SET reported_at = ?, report = ? WHERE id = ?
`

type SaveHostReportParams struct {
	ReportedAt sql.NullString
	Report     sql.NullString
	ID         string
}

func (q *Queries) SaveHostReport(ctx context.Context, arg SaveHostReportParams) error {
	_, err := q.db.ExecContext(ctx, saveHostReport, arg.ReportedAt, arg.Report, arg.ID)
	return err
}

const setHostToken = `-- name: SetHostToken :execrows
UPDATE hosts SET token_hash = ? WHERE name = ?
`

type SetHostTokenParams struct {
	TokenHash string
	Name      string
}

func (q *Queries) SetHostToken(ctx context.Context, arg SetHostTokenParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setHostToken, arg.TokenHash, arg.Name)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
