// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: jobs.sql

package db

import (
	"context"
	"database/sql"
)

const getJob = `-- name: GetJob :one
SELECT id, slug, name, command, schedule, grace_seconds, created_at, updated_at FROM jobs WHERE id = ?
`

func (q *Queries) GetJob(ctx context.Context, id string) (Job, error) {
	row := q.db.QueryRowContext(ctx, getJob, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Command,
		&i.Schedule,
		&i.GraceSeconds,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getJobBySlug = `-- name: GetJobBySlug :one
SELECT id, slug, name, command, schedule, grace_seconds, created_at, updated_at FROM jobs WHERE slug = ?
`

func (q *Queries) GetJobBySlug(ctx context.Context, slug string) (Job, error) {
	row := q.db.QueryRowContext(ctx, getJobBySlug, slug)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Command,
		&i.Schedule,
		&i.GraceSeconds,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listJobs = `-- name: ListJobs :many
SELECT id, slug, name, command, schedule, grace_seconds, created_at, updated_at FROM jobs ORDER BY name COLLATE NOCASE
`

func (q *Queries) ListJobs(ctx context.Context) ([]Job, error) {
	rows, err := q.db.QueryContext(ctx, listJobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Job
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Command,
			&i.Schedule,
			&i.GraceSeconds,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertJob = `-- name: UpsertJob :exec
INSERT INTO jobs (id, slug, name, command, schedule, grace_seconds, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(slug) DO UPDATE SET
    name = excluded.name,
    command = excluded.command,
    schedule = excluded.schedule,
    grace_seconds = excluded.grace_seconds,
    updated_at = excluded.updated_at
`

type UpsertJobParams struct {
	ID           string
	Slug         string
	Name         string
	Command      string
	Schedule     sql.NullString
	GraceSeconds int64
	CreatedAt    string
	UpdatedAt    string
}

func (q *Queries) UpsertJob(ctx context.Context, arg UpsertJobParams) error {
	_, err := q.db.ExecContext(ctx, upsertJob,
		arg.ID,
		arg.Slug,
		arg.Name,
		arg.Command,
		arg.Schedule,
		arg.GraceSeconds,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
