// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: jobs.sql

package db

import (
	"context"
	"database/sql"
)

const archiveJob = `-- name: ArchiveJob :exec
UPDATE jobs SET archived_at = ?, paused_at = NULL, paused_until = NULL, updated_at = ? WHERE id = ?
`

type ArchiveJobParams struct {
	ArchivedAt sql.NullString
	UpdatedAt  string
	ID         string
}

func (q *Queries) ArchiveJob(ctx context.Context, arg ArchiveJobParams) error {
	_, err := q.db.ExecContext(ctx, archiveJob, arg.ArchivedAt, arg.UpdatedAt, arg.ID)
	return err
}

const getJob = `-- name: GetJob :one
SELECT id, slug, name, command, schedule, grace_seconds, created_at, updated_at, missed_checked_until, on_failure, on_recover, max_duration_seconds, in_crontab, paused_at, paused_until, archived_at FROM jobs WHERE id = ?
`

func (q *Queries) GetJob(ctx context.Context, id string) (Job, error) {
	row := q.db.QueryRowContext(ctx, getJob, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Command,
		&i.Schedule,
		&i.GraceSeconds,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MissedCheckedUntil,
		&i.OnFailure,
		&i.OnRecover,
		&i.MaxDurationSeconds,
		&i.InCrontab,
		&i.PausedAt,
		&i.PausedUntil,
		&i.ArchivedAt,
	)
	return i, err
}

const getJobBySlug = `-- name: GetJobBySlug :one
SELECT id, slug, name, command, schedule, grace_seconds, created_at, updated_at, missed_checked_until, on_failure, on_recover, max_duration_seconds, in_crontab, paused_at, paused_until, archived_at FROM jobs WHERE slug = ?
`

func (q *Queries) GetJobBySlug(ctx context.Context, slug string) (Job, error) {
	row := q.db.QueryRowContext(ctx, getJobBySlug, slug)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Command,
		&i.Schedule,
		&i.GraceSeconds,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MissedCheckedUntil,
		&i.OnFailure,
		&i.OnRecover,
		&i.MaxDurationSeconds,
		&i.InCrontab,
		&i.PausedAt,
		&i.PausedUntil,
		&i.ArchivedAt,
	)
	return i, err
}

const listJobs = `-- name: ListJobs :many
SELECT id, slug, name, command, schedule, grace_seconds, created_at, updated_at, missed_checked_until, on_failure, on_recover, max_duration_seconds, in_crontab, paused_at, paused_until, archived_at FROM jobs ORDER BY name COLLATE NOCASE
`

func (q *Queries) ListJobs(ctx context.Context) ([]Job, error) {
	rows, err := q.db.QueryContext(ctx, listJobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Job
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Command,
			&i.Schedule,
			&i.GraceSeconds,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.MissedCheckedUntil,
			&i.OnFailure,
			&i.OnRecover,
			&i.MaxDurationSeconds,
			&i.InCrontab,
			&i.PausedAt,
			&i.PausedUntil,
			&i.ArchivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobsInCrontab = `-- name: ListJobsInCrontab :many
SELECT id, slug, name, command, schedule, grace_seconds, created_at, updated_at, missed_checked_until, on_failure, on_recover, max_duration_seconds, in_crontab, paused_at, paused_until, archived_at FROM jobs WHERE in_crontab = 1 ORDER BY slug
`

func (q *Queries) ListJobsInCrontab(ctx context.Context) ([]Job, error) {
	rows, err := q.db.QueryContext(ctx, listJobsInCrontab)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Job
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Command,
			&i.Schedule,
			&i.GraceSeconds,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.MissedCheckedUntil,
			&i.OnFailure,
			&i.OnRecover,
			&i.MaxDurationSeconds,
			&i.InCrontab,
			&i.PausedAt,
			&i.PausedUntil,
			&i.ArchivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markJobInCrontab = `-- name: MarkJobInCrontab :exec
UPDATE jobs SET in_crontab = 1 WHERE slug = ?
`

func (q *Queries) MarkJobInCrontab(ctx context.Context, slug string) error {
	_, err := q.db.ExecContext(ctx, markJobInCrontab, slug)
	return err
}

const pauseJob = `-- name: PauseJob :exec
UPDATE jobs SET paused_at = ?, paused_until = ?, updated_at = ? WHERE id = ?
`

type PauseJobParams struct {
	PausedAt    sql.NullString
	PausedUntil sql.NullString
	UpdatedAt   string
	ID          string
}

func (q *Queries) PauseJob(ctx context.Context, arg PauseJobParams) error {
	_, err := q.db.ExecContext(ctx, pauseJob,
		arg.PausedAt,
		arg.PausedUntil,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const removeJobFromCrontab = `-- name: RemoveJobFromCrontab :exec
UPDATE jobs SET in_crontab = 0, schedule = NULL, updated_at = ?,
    missed_checked_until = CASE WHEN schedule IS NULL THEN missed_checked_until ELSE ? END
WHERE id = ?
`

type RemoveJobFromCrontabParams struct {
	UpdatedAt          string
	MissedCheckedUntil sql.NullString
	ID                 string
}

// The job's line left the crontab: it is no longer expected on a schedule.
func (q *Queries) RemoveJobFromCrontab(ctx context.Context, arg RemoveJobFromCrontabParams) error {
	_, err := q.db.ExecContext(ctx, removeJobFromCrontab, arg.UpdatedAt, arg.MissedCheckedUntil, arg.ID)
	return err
}

const resumeJob = `-- name: ResumeJob :exec
UPDATE jobs SET paused_at = NULL, paused_until = NULL, archived_at = NULL,
    missed_checked_until = ?, updated_at = ?
WHERE id = ?
`

type ResumeJobParams struct {
	MissedCheckedUntil sql.NullString
	UpdatedAt          string
	ID                 string
}

// Missed runs are checked from now, not from before the pause.
func (q *Queries) ResumeJob(ctx context.Context, arg ResumeJobParams) error {
	_, err := q.db.ExecContext(ctx, resumeJob, arg.MissedCheckedUntil, arg.UpdatedAt, arg.ID)
	return err
}

const setMissedCheckedUntil = `-- name: SetMissedCheckedUntil :exec
UPDATE jobs SET missed_checked_until = ? WHERE id = ?
`

type SetMissedCheckedUntilParams struct {
	MissedCheckedUntil sql.NullString
	ID                 string
}

func (q *Queries) SetMissedCheckedUntil(ctx context.Context, arg SetMissedCheckedUntilParams) error {
	_, err := q.db.ExecContext(ctx, setMissedCheckedUntil, arg.MissedCheckedUntil, arg.ID)
	return err
}

const upsertJob = `-- name: UpsertJob :exec
INSERT INTO jobs (id, slug, name, command, schedule, grace_seconds, on_failure, on_recover, max_duration_seconds, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(slug) DO UPDATE SET
    name = excluded.name,
    command = excluded.command,
    schedule = excluded.schedule,
    grace_seconds = excluded.grace_seconds,
    on_failure = excluded.on_failure,
    on_recover = excluded.on_recover,
    max_duration_seconds = excluded.max_duration_seconds,
    updated_at = excluded.updated_at,
    -- A new schedule must not be judged against occurrences before it existed.
    missed_checked_until = CASE WHEN jobs.schedule IS excluded.schedule
        THEN jobs.missed_checked_until ELSE excluded.updated_at END
`

type UpsertJobParams struct {
	ID                 string
	Slug               string
	Name               string
	Command            string
	Schedule           sql.NullString
	GraceSeconds       int64
	OnFailure          sql.NullString
	OnRecover          sql.NullString
	MaxDurationSeconds sql.NullInt64
	CreatedAt          string
	UpdatedAt          string
}

func (q *Queries) UpsertJob(ctx context.Context, arg UpsertJobParams) error {
	_, err := q.db.ExecContext(ctx, upsertJob,
		arg.ID,
		arg.Slug,
		arg.Name,
		arg.Command,
		arg.Schedule,
		arg.GraceSeconds,
		arg.OnFailure,
		arg.OnRecover,
		arg.MaxDurationSeconds,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
