// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: missed.sql

package db

import (
	"context"
)

const latestMissedOccurrence = `-- name: LatestMissedOccurrence :one
SELECT expected_at FROM missed_occurrences WHERE job_id = ? ORDER BY expected_at DESC LIMIT 1
`

func (q *Queries) LatestMissedOccurrence(ctx context.Context, jobID string) (string, error) {
	row := q.db.QueryRowContext(ctx, latestMissedOccurrence, jobID)
	var expected_at string
	err := row.Scan(&expected_at)
	return expected_at, err
}

const recordMissedOccurrence = `-- name: RecordMissedOccurrence :exec
INSERT OR IGNORE INTO missed_occurrences (id, job_id, expected_at, detected_at)
VALUES (?, ?, ?, ?)
`

type RecordMissedOccurrenceParams struct {
	ID         string
	JobID      string
	ExpectedAt string
	DetectedAt string
}

func (q *Queries) RecordMissedOccurrence(ctx context.Context, arg RecordMissedOccurrenceParams) error {
	_, err := q.db.ExecContext(ctx, recordMissedOccurrence,
		arg.ID,
		arg.JobID,
		arg.ExpectedAt,
		arg.DetectedAt,
	)
	return err
}
