// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
)

type Alert struct {
	ID            string
	JobID         string
	RunID         sql.NullString
	Event         string
	Hook          string
	Environ       string
	CreatedAt     string
	Status        string
	Attempts      int64
	NextAttemptAt sql.NullString
	LastAttemptAt sql.NullString
	LastError     string
	LastOutput    string
}

type CrontabChange struct {
	ID         string
	SnapshotID string
	TakenAt    string
	JobSlug    sql.NullString
	Kind       string
	BeforeText string
	AfterText  string
}

type CrontabSnapshot struct {
	ID          string
	TakenAt     string
	ContentHash string
	Content     string
}

type Environment struct {
	Hash      string
	Data      string
	CreatedAt string
}

type Job struct {
	ID                 string
	Slug               string
	Name               string
	Command            string
	Schedule           sql.NullString
	GraceSeconds       int64
	CreatedAt          string
	UpdatedAt          string
	MissedCheckedUntil sql.NullString
	OnFailure          sql.NullString
	OnRecover          sql.NullString
	MaxDurationSeconds sql.NullInt64
}

type MissedOccurrence struct {
	ID         string
	JobID      string
	ExpectedAt string
	DetectedAt string
}

type Run struct {
	ID               string
	JobID            string
	StartedAt        string
	EndedAt          sql.NullString
	DurationMs       sql.NullInt64
	Status           string
	ExitCode         sql.NullInt64
	Stdout           string
	Stderr           string
	CombinedLog      string
	Truncated        int64
	CreatedAt        string
	Pid              sql.NullInt64
	Host             sql.NullString
	EnvHash          sql.NullString
	Reason           sql.NullString
	OverlappedRunID  sql.NullString
	MaxRssKb         sql.NullInt64
	UserCpuMs        sql.NullInt64
	SysCpuMs         sql.NullInt64
	FailureSignature sql.NullString
}
