// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
)

type Environment struct {
	Hash      string
	Data      string
	CreatedAt string
}

type Job struct {
	ID                 string
	Slug               string
	Name               string
	Command            string
	Schedule           sql.NullString
	GraceSeconds       int64
	CreatedAt          string
	UpdatedAt          string
	MissedCheckedUntil sql.NullString
}

type MissedOccurrence struct {
	ID         string
	JobID      string
	ExpectedAt string
	DetectedAt string
}

type Run struct {
	ID          string
	JobID       string
	StartedAt   string
	EndedAt     sql.NullString
	DurationMs  sql.NullInt64
	Status      string
	ExitCode    sql.NullInt64
	Stdout      string
	Stderr      string
	CombinedLog string
	Truncated   int64
	CreatedAt   string
	Pid         sql.NullInt64
	Host        sql.NullString
	EnvHash     sql.NullString
}
