// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: runs.sql

package db

import (
	"context"
	"database/sql"
)

const countRunsSince = `-- name: CountRunsSince :many
SELECT job_id, status, count(*) AS runs FROM runs WHERE started_at >= ? GROUP BY job_id, status
`

type CountRunsSinceRow struct {
	JobID  string
	Status string
	Runs   int64
}

func (q *Queries) CountRunsSince(ctx context.Context, startedAt string) ([]CountRunsSinceRow, error) {
	rows, err := q.db.QueryContext(ctx, countRunsSince, startedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountRunsSinceRow
	for rows.Next() {
		var i CountRunsSinceRow
		if err := rows.Scan(&i.JobID, &i.Status, &i.Runs); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createRun = `-- name: CreateRun :exec
INSERT INTO runs (id, job_id, started_at, status, created_at, pid, host)
VALUES (?, ?, ?, 'running', ?, ?, ?)
`

type CreateRunParams struct {
	ID        string
	JobID     string
	StartedAt string
	CreatedAt string
	Pid       sql.NullInt64
	Host      sql.NullString
}

func (q *Queries) CreateRun(ctx context.Context, arg CreateRunParams) error {
	_, err := q.db.ExecContext(ctx, createRun,
		arg.ID,
		arg.JobID,
		arg.StartedAt,
		arg.CreatedAt,
		arg.Pid,
		arg.Host,
	)
	return err
}

const deleteRunsBefore = `-- name: DeleteRunsBefore :execrows
DELETE FROM runs WHERE status != 'running' AND started_at < ?
`

func (q *Queries) DeleteRunsBefore(ctx context.Context, startedAt string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteRunsBefore, startedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteRunsBeyondKeep = `-- name: DeleteRunsBeyondKeep :execrows
DELETE FROM runs WHERE status != 'running' AND started_at < COALESCE((
    SELECT kept.started_at FROM runs AS kept
    WHERE kept.job_id = runs.job_id
    ORDER BY kept.started_at DESC LIMIT 1 OFFSET ?
), '')
`

// The parameter is keep-1: the offset of the oldest run to keep for each job.
func (q *Queries) DeleteRunsBeyondKeep(ctx context.Context, offset int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteRunsBeyondKeep, offset)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const failureHistoryBefore = `-- name: FailureHistoryBefore :one
SELECT count(*) AS runs, CAST(coalesce(min(started_at), '') AS TEXT) AS first_seen
FROM runs WHERE job_id = ? AND failure_signature = ? AND started_at < ?
`

type FailureHistoryBeforeParams struct {
	JobID            string
	FailureSignature sql.NullString
	StartedAt        string
}

type FailureHistoryBeforeRow struct {
	Runs      int64
	FirstSeen string
}

// How many earlier runs of the job failed the same way, and when the first did.
func (q *Queries) FailureHistoryBefore(ctx context.Context, arg FailureHistoryBeforeParams) (FailureHistoryBeforeRow, error) {
	row := q.db.QueryRowContext(ctx, failureHistoryBefore, arg.JobID, arg.FailureSignature, arg.StartedAt)
	var i FailureHistoryBeforeRow
	err := row.Scan(&i.Runs, &i.FirstSeen)
	return i, err
}

const finishRun = `-- name: FinishRun :execrows
UPDATE runs SET ended_at = ?, duration_ms = ?, status = ?, exit_code = ?,
    stdout = ?, stderr = ?, combined_log = ?, truncated = ?, reason = ?,
    max_rss_kb = ?, user_cpu_ms = ?, sys_cpu_ms = ?, failure_signature = ?
WHERE id = ? AND status = 'running'
`

type FinishRunParams struct {
	EndedAt          sql.NullString
	DurationMs       sql.NullInt64
	Status           string
	ExitCode         sql.NullInt64
	Stdout           string
	Stderr           string
	CombinedLog      string
	Truncated        int64
	Reason           sql.NullString
	MaxRssKb         sql.NullInt64
	UserCpuMs        sql.NullInt64
	SysCpuMs         sql.NullInt64
	FailureSignature sql.NullString
	ID               string
}

func (q *Queries) FinishRun(ctx context.Context, arg FinishRunParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, finishRun,
		arg.EndedAt,
		arg.DurationMs,
		arg.Status,
		arg.ExitCode,
		arg.Stdout,
		arg.Stderr,
		arg.CombinedLog,
		arg.Truncated,
		arg.Reason,
		arg.MaxRssKb,
		arg.UserCpuMs,
		arg.SysCpuMs,
		arg.FailureSignature,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getRun = `-- name: GetRun :one
SELECT id, job_id, started_at, ended_at, duration_ms, status, exit_code, stdout, stderr, combined_log, truncated, created_at, pid, host, env_hash, reason, overlapped_run_id, max_rss_kb, user_cpu_ms, sys_cpu_ms, failure_signature FROM runs WHERE id = ?
`

func (q *Queries) GetRun(ctx context.Context, id string) (Run, error) {
	row := q.db.QueryRowContext(ctx, getRun, id)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.StartedAt,
		&i.EndedAt,
		&i.DurationMs,
		&i.Status,
		&i.ExitCode,
		&i.Stdout,
		&i.Stderr,
		&i.CombinedLog,
		&i.Truncated,
		&i.CreatedAt,
		&i.Pid,
		&i.Host,
		&i.EnvHash,
		&i.Reason,
		&i.OverlappedRunID,
		&i.MaxRssKb,
		&i.UserCpuMs,
		&i.SysCpuMs,
		&i.FailureSignature,
	)
	return i, err
}

const lastSuccessBefore = `-- name: LastSuccessBefore :one
SELECT id, job_id, started_at, ended_at, duration_ms, status, exit_code, stdout, stderr, combined_log, truncated, created_at, pid, host, env_hash, reason, overlapped_run_id, max_rss_kb, user_cpu_ms, sys_cpu_ms, failure_signature FROM runs WHERE job_id = ? AND status = 'success' AND started_at < ?
ORDER BY started_at DESC LIMIT 1
`

type LastSuccessBeforeParams struct {
	JobID     string
	StartedAt string
}

func (q *Queries) LastSuccessBefore(ctx context.Context, arg LastSuccessBeforeParams) (Run, error) {
	row := q.db.QueryRowContext(ctx, lastSuccessBefore, arg.JobID, arg.StartedAt)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.StartedAt,
		&i.EndedAt,
		&i.DurationMs,
		&i.Status,
		&i.ExitCode,
		&i.Stdout,
		&i.Stderr,
		&i.CombinedLog,
		&i.Truncated,
		&i.CreatedAt,
		&i.Pid,
		&i.Host,
		&i.EnvHash,
		&i.Reason,
		&i.OverlappedRunID,
		&i.MaxRssKb,
		&i.UserCpuMs,
		&i.SysCpuMs,
		&i.FailureSignature,
	)
	return i, err
}

const lastSuccessWithEnvBefore = `-- name: LastSuccessWithEnvBefore :one
SELECT id, job_id, started_at, ended_at, duration_ms, status, exit_code, stdout, stderr, combined_log, truncated, created_at, pid, host, env_hash, reason, overlapped_run_id, max_rss_kb, user_cpu_ms, sys_cpu_ms, failure_signature FROM runs
WHERE job_id = ? AND status = 'success' AND env_hash IS NOT NULL AND started_at < ?
ORDER BY started_at DESC LIMIT 1
`

type LastSuccessWithEnvBeforeParams struct {
	JobID     string
	StartedAt string
}

func (q *Queries) LastSuccessWithEnvBefore(ctx context.Context, arg LastSuccessWithEnvBeforeParams) (Run, error) {
	row := q.db.QueryRowContext(ctx, lastSuccessWithEnvBefore, arg.JobID, arg.StartedAt)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.StartedAt,
		&i.EndedAt,
		&i.DurationMs,
		&i.Status,
		&i.ExitCode,
		&i.Stdout,
		&i.Stderr,
		&i.CombinedLog,
		&i.Truncated,
		&i.CreatedAt,
		&i.Pid,
		&i.Host,
		&i.EnvHash,
		&i.Reason,
		&i.OverlappedRunID,
		&i.MaxRssKb,
		&i.UserCpuMs,
		&i.SysCpuMs,
		&i.FailureSignature,
	)
	return i, err
}

const latestRunWithEnv = `-- name: LatestRunWithEnv :one
SELECT id, job_id, started_at, ended_at, duration_ms, status, exit_code, stdout, stderr, combined_log, truncated, created_at, pid, host, env_hash, reason, overlapped_run_id, max_rss_kb, user_cpu_ms, sys_cpu_ms, failure_signature FROM runs WHERE job_id = ? AND env_hash IS NOT NULL
ORDER BY started_at DESC LIMIT 1
`

func (q *Queries) LatestRunWithEnv(ctx context.Context, jobID string) (Run, error) {
	row := q.db.QueryRowContext(ctx, latestRunWithEnv, jobID)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.StartedAt,
		&i.EndedAt,
		&i.DurationMs,
		&i.Status,
		&i.ExitCode,
		&i.Stdout,
		&i.Stderr,
		&i.CombinedLog,
		&i.Truncated,
		&i.CreatedAt,
		&i.Pid,
		&i.Host,
		&i.EnvHash,
		&i.Reason,
		&i.OverlappedRunID,
		&i.MaxRssKb,
		&i.UserCpuMs,
		&i.SysCpuMs,
		&i.FailureSignature,
	)
	return i, err
}

const latestRunningRunBefore = `-- name: LatestRunningRunBefore :one
SELECT id, job_id, started_at, ended_at, duration_ms, status, exit_code, stdout, stderr, combined_log, truncated, created_at, pid, host, env_hash, reason, overlapped_run_id, max_rss_kb, user_cpu_ms, sys_cpu_ms, failure_signature FROM runs WHERE job_id = ? AND status = 'running' AND id != ?
ORDER BY started_at DESC LIMIT 1
`

type LatestRunningRunBeforeParams struct {
	JobID string
	ID    string
}

func (q *Queries) LatestRunningRunBefore(ctx context.Context, arg LatestRunningRunBeforeParams) (Run, error) {
	row := q.db.QueryRowContext(ctx, latestRunningRunBefore, arg.JobID, arg.ID)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.StartedAt,
		&i.EndedAt,
		&i.DurationMs,
		&i.Status,
		&i.ExitCode,
		&i.Stdout,
		&i.Stderr,
		&i.CombinedLog,
		&i.Truncated,
		&i.CreatedAt,
		&i.Pid,
		&i.Host,
		&i.EnvHash,
		&i.Reason,
		&i.OverlappedRunID,
		&i.MaxRssKb,
		&i.UserCpuMs,
		&i.SysCpuMs,
		&i.FailureSignature,
	)
	return i, err
}

const listFailureGroups = `-- name: ListFailureGroups :many
SELECT g.failure_signature, count(*) AS runs, CAST(min(g.started_at) AS TEXT) AS first_seen,
    CAST(max(g.started_at) AS TEXT) AS last_seen,
    CAST((SELECT latest.id FROM runs AS latest WHERE latest.job_id = g.job_id
        AND latest.failure_signature = g.failure_signature
        ORDER BY latest.started_at DESC LIMIT 1) AS TEXT) AS latest_run_id
FROM runs AS g WHERE g.job_id = ? AND g.failure_signature IS NOT NULL
GROUP BY g.failure_signature ORDER BY last_seen DESC LIMIT ?
`

type ListFailureGroupsParams struct {
	JobID string
	Limit int64
}

type ListFailureGroupsRow struct {
	FailureSignature sql.NullString
	Runs             int64
	FirstSeen        string
	LastSeen         string
	LatestRunID      string
}

// The job's distinct failure signatures, most recent first, with the newest
// run of each.
func (q *Queries) ListFailureGroups(ctx context.Context, arg ListFailureGroupsParams) ([]ListFailureGroupsRow, error) {
	rows, err := q.db.QueryContext(ctx, listFailureGroups, arg.JobID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFailureGroupsRow
	for rows.Next() {
		var i ListFailureGroupsRow
		if err := rows.Scan(
			&i.FailureSignature,
			&i.Runs,
			&i.FirstSeen,
			&i.LastSeen,
			&i.LatestRunID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunDurations = `-- name: ListRunDurations :many
SELECT id, started_at, duration_ms, status FROM runs
WHERE job_id = ? AND status NOT IN ('running', 'skipped') AND duration_ms IS NOT NULL
ORDER BY started_at DESC LIMIT ?
`

type ListRunDurationsParams struct {
	JobID string
	Limit int64
}

type ListRunDurationsRow struct {
	ID         string
	StartedAt  string
	DurationMs sql.NullInt64
	Status     string
}

// The job's newest finished runs, without their output.
func (q *Queries) ListRunDurations(ctx context.Context, arg ListRunDurationsParams) ([]ListRunDurationsRow, error) {
	rows, err := q.db.QueryContext(ctx, listRunDurations, arg.JobID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRunDurationsRow
	for rows.Next() {
		var i ListRunDurationsRow
		if err := rows.Scan(
			&i.ID,
			&i.StartedAt,
			&i.DurationMs,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunStartsSince = `-- name: ListRunStartsSince :many
SELECT started_at FROM runs WHERE job_id = ? AND started_at >= ? ORDER BY started_at
`

type ListRunStartsSinceParams struct {
	JobID     string
	StartedAt string
}

func (q *Queries) ListRunStartsSince(ctx context.Context, arg ListRunStartsSinceParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listRunStartsSince, arg.JobID, arg.StartedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var started_at string
		if err := rows.Scan(&started_at); err != nil {
			return nil, err
		}
		items = append(items, started_at)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunningRuns = `-- name: ListRunningRuns :many
SELECT id, job_id, started_at, ended_at, duration_ms, status, exit_code, stdout, stderr, combined_log, truncated, created_at, pid, host, env_hash, reason, overlapped_run_id, max_rss_kb, user_cpu_ms, sys_cpu_ms, failure_signature FROM runs WHERE status = 'running'
`

func (q *Queries) ListRunningRuns(ctx context.Context) ([]Run, error) {
	rows, err := q.db.QueryContext(ctx, listRunningRuns)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Run
	for rows.Next() {
		var i Run
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.StartedAt,
			&i.EndedAt,
			&i.DurationMs,
			&i.Status,
			&i.ExitCode,
			&i.Stdout,
			&i.Stderr,
			&i.CombinedLog,
			&i.Truncated,
			&i.CreatedAt,
			&i.Pid,
			&i.Host,
			&i.EnvHash,
			&i.Reason,
			&i.OverlappedRunID,
			&i.MaxRssKb,
			&i.UserCpuMs,
			&i.SysCpuMs,
			&i.FailureSignature,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunsForJob = `-- name: ListRunsForJob :many
SELECT id, job_id, started_at, ended_at, duration_ms, status, exit_code, stdout, stderr, combined_log, truncated, created_at, pid, host, env_hash, reason, overlapped_run_id, max_rss_kb, user_cpu_ms, sys_cpu_ms, failure_signature FROM runs WHERE job_id = ? ORDER BY started_at DESC LIMIT ?
`

type ListRunsForJobParams struct {
	JobID string
	Limit int64
}

func (q *Queries) ListRunsForJob(ctx context.Context, arg ListRunsForJobParams) ([]Run, error) {
	rows, err := q.db.QueryContext(ctx, listRunsForJob, arg.JobID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Run
	for rows.Next() {
		var i Run
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.StartedAt,
			&i.EndedAt,
			&i.DurationMs,
			&i.Status,
			&i.ExitCode,
			&i.Stdout,
			&i.Stderr,
			&i.CombinedLog,
			&i.Truncated,
			&i.CreatedAt,
			&i.Pid,
			&i.Host,
			&i.EnvHash,
			&i.Reason,
			&i.OverlappedRunID,
			&i.MaxRssKb,
			&i.UserCpuMs,
			&i.SysCpuMs,
			&i.FailureSignature,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunsOverlapping = `-- name: ListRunsOverlapping :many
SELECT id, job_id, started_at, ended_at, duration_ms, status, exit_code, reason, overlapped_run_id
FROM runs WHERE started_at < ?1 AND (ended_at IS NULL OR ended_at >= ?2)
ORDER BY started_at
`

type ListRunsOverlappingParams struct {
	ToTime   string
	FromTime sql.NullString
}

type ListRunsOverlappingRow struct {
	ID              string
	JobID           string
	StartedAt       string
	EndedAt         sql.NullString
	DurationMs      sql.NullInt64
	Status          string
	ExitCode        sql.NullInt64
	Reason          sql.NullString
	OverlappedRunID sql.NullString
}

// Runs that were running at some point in [from, to): started before to and
// not ended before from.
func (q *Queries) ListRunsOverlapping(ctx context.Context, arg ListRunsOverlappingParams) ([]ListRunsOverlappingRow, error) {
	rows, err := q.db.QueryContext(ctx, listRunsOverlapping, arg.ToTime, arg.FromTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRunsOverlappingRow
	for rows.Next() {
		var i ListRunsOverlappingRow
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.StartedAt,
			&i.EndedAt,
			&i.DurationMs,
			&i.Status,
			&i.ExitCode,
			&i.Reason,
			&i.OverlappedRunID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunsWithJob = `-- name: ListRunsWithJob :many
SELECT runs.id, runs.job_id, runs.started_at, runs.ended_at, runs.duration_ms, runs.status, runs.exit_code, runs.stdout, runs.stderr, runs.combined_log, runs.truncated, runs.created_at, runs.pid, runs.host, runs.env_hash, runs.reason, runs.overlapped_run_id, runs.max_rss_kb, runs.user_cpu_ms, runs.sys_cpu_ms, runs.failure_signature, jobs.name AS job_name
FROM runs JOIN jobs ON jobs.id = runs.job_id
ORDER BY runs.started_at DESC LIMIT ?
`

type ListRunsWithJobRow struct {
	Run     Run
	JobName string
}

func (q *Queries) ListRunsWithJob(ctx context.Context, limit int64) ([]ListRunsWithJobRow, error) {
	rows, err := q.db.QueryContext(ctx, listRunsWithJob, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRunsWithJobRow
	for rows.Next() {
		var i ListRunsWithJobRow
		if err := rows.Scan(
			&i.Run.ID,
			&i.Run.JobID,
			&i.Run.StartedAt,
			&i.Run.EndedAt,
			&i.Run.DurationMs,
			&i.Run.Status,
			&i.Run.ExitCode,
			&i.Run.Stdout,
			&i.Run.Stderr,
			&i.Run.CombinedLog,
			&i.Run.Truncated,
			&i.Run.CreatedAt,
			&i.Run.Pid,
			&i.Run.Host,
			&i.Run.EnvHash,
			&i.Run.Reason,
			&i.Run.OverlappedRunID,
			&i.Run.MaxRssKb,
			&i.Run.UserCpuMs,
			&i.Run.SysCpuMs,
			&i.Run.FailureSignature,
			&i.JobName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnsignedFailures = `-- name: ListUnsignedFailures :many
SELECT id, status, exit_code, stdout, stderr, reason FROM runs
WHERE failure_signature IS NULL AND status IN ('failed', 'timeout')
LIMIT ?
`

type ListUnsignedFailuresRow struct {
	ID       string
	Status   string
	ExitCode sql.NullInt64
	Stdout   string
	Stderr   string
	Reason   sql.NullString
}

func (q *Queries) ListUnsignedFailures(ctx context.Context, limit int64) ([]ListUnsignedFailuresRow, error) {
	rows, err := q.db.QueryContext(ctx, listUnsignedFailures, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUnsignedFailuresRow
	for rows.Next() {
		var i ListUnsignedFailuresRow
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.ExitCode,
			&i.Stdout,
			&i.Stderr,
			&i.Reason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const previousFinishedRun = `-- name: PreviousFinishedRun :one
SELECT id, job_id, started_at, ended_at, duration_ms, status, exit_code, stdout, stderr, combined_log, truncated, created_at, pid, host, env_hash, reason, overlapped_run_id, max_rss_kb, user_cpu_ms, sys_cpu_ms, failure_signature FROM runs
WHERE job_id = ? AND status NOT IN ('running', 'skipped') AND started_at < ?
ORDER BY started_at DESC LIMIT 1
`

type PreviousFinishedRunParams struct {
	JobID     string
	StartedAt string
}

// The job's newest finished run before the given start, ignoring skipped runs.
func (q *Queries) PreviousFinishedRun(ctx context.Context, arg PreviousFinishedRunParams) (Run, error) {
	row := q.db.QueryRowContext(ctx, previousFinishedRun, arg.JobID, arg.StartedAt)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.StartedAt,
		&i.EndedAt,
		&i.DurationMs,
		&i.Status,
		&i.ExitCode,
		&i.Stdout,
		&i.Stderr,
		&i.CombinedLog,
		&i.Truncated,
		&i.CreatedAt,
		&i.Pid,
		&i.Host,
		&i.EnvHash,
		&i.Reason,
		&i.OverlappedRunID,
		&i.MaxRssKb,
		&i.UserCpuMs,
		&i.SysCpuMs,
		&i.FailureSignature,
	)
	return i, err
}

const searchRunLogs = `-- name: SearchRunLogs :many
SELECT runs.id, runs.job_id, runs.started_at, runs.ended_at, runs.duration_ms, runs.status, runs.exit_code, runs.stdout, runs.stderr, runs.combined_log, runs.truncated, runs.created_at, runs.pid, runs.host, runs.env_hash, runs.reason, runs.overlapped_run_id, runs.max_rss_kb, runs.user_cpu_ms, runs.sys_cpu_ms, runs.failure_signature, jobs.name AS job_name
FROM runs JOIN jobs ON jobs.id = runs.job_id
WHERE runs.status != 'running'
  AND instr(lower(runs.combined_log), lower(?1)) > 0
ORDER BY runs.started_at DESC LIMIT ?2
`

type SearchRunLogsParams struct {
	Query    string
	RowLimit int64
}

type SearchRunLogsRow struct {
	Run     Run
	JobName string
}

func (q *Queries) SearchRunLogs(ctx context.Context, arg SearchRunLogsParams) ([]SearchRunLogsRow, error) {
	rows, err := q.db.QueryContext(ctx, searchRunLogs, arg.Query, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchRunLogsRow
	for rows.Next() {
		var i SearchRunLogsRow
		if err := rows.Scan(
			&i.Run.ID,
			&i.Run.JobID,
			&i.Run.StartedAt,
			&i.Run.EndedAt,
			&i.Run.DurationMs,
			&i.Run.Status,
			&i.Run.ExitCode,
			&i.Run.Stdout,
			&i.Run.Stderr,
			&i.Run.CombinedLog,
			&i.Run.Truncated,
			&i.Run.CreatedAt,
			&i.Run.Pid,
			&i.Run.Host,
			&i.Run.EnvHash,
			&i.Run.Reason,
			&i.Run.OverlappedRunID,
			&i.Run.MaxRssKb,
			&i.Run.UserCpuMs,
			&i.Run.SysCpuMs,
			&i.Run.FailureSignature,
			&i.JobName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setFailureSignature = `-- name: SetFailureSignature :exec
UPDATE runs SET failure_signature = ? WHERE id = ?
`

type SetFailureSignatureParams struct {
	FailureSignature sql.NullString
	ID               string
}

func (q *Queries) SetFailureSignature(ctx context.Context, arg SetFailureSignatureParams) error {
	_, err := q.db.ExecContext(ctx, setFailureSignature, arg.FailureSignature, arg.ID)
	return err
}

const setRunEnv = `-- name: SetRunEnv :exec
UPDATE runs SET env_hash = ? WHERE id = ?
`

type SetRunEnvParams struct {
	EnvHash sql.NullString
	ID      string
}

func (q *Queries) SetRunEnv(ctx context.Context, arg SetRunEnvParams) error {
	_, err := q.db.ExecContext(ctx, setRunEnv, arg.EnvHash, arg.ID)
	return err
}

const setRunOverlap = `-- name: SetRunOverlap :exec
UPDATE runs SET overlapped_run_id = ? WHERE id = ?
`

type SetRunOverlapParams struct {
	OverlappedRunID sql.NullString
	ID              string
}

func (q *Queries) SetRunOverlap(ctx context.Context, arg SetRunOverlapParams) error {
	_, err := q.db.ExecContext(ctx, setRunOverlap, arg.OverlappedRunID, arg.ID)
	return err
}

const successDurationsBefore = `-- name: SuccessDurationsBefore :many
SELECT duration_ms FROM runs
WHERE job_id = ? AND status = 'success' AND started_at < ? AND duration_ms IS NOT NULL
ORDER BY started_at DESC LIMIT ?
`

type SuccessDurationsBeforeParams struct {
	JobID     string
	StartedAt string
	Limit     int64
}

func (q *Queries) SuccessDurationsBefore(ctx context.Context, arg SuccessDurationsBeforeParams) ([]sql.NullInt64, error) {
	rows, err := q.db.QueryContext(ctx, successDurationsBefore, arg.JobID, arg.StartedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []sql.NullInt64
	for rows.Next() {
		var duration_ms sql.NullInt64
		if err := rows.Scan(&duration_ms); err != nil {
			return nil, err
		}
		items = append(items, duration_ms)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const successDurationsSince = `-- name: SuccessDurationsSince :many
SELECT started_at, duration_ms FROM runs
WHERE job_id = ? AND status = 'success' AND started_at >= ? AND duration_ms IS NOT NULL
ORDER BY started_at
`

type SuccessDurationsSinceParams struct {
	JobID     string
	StartedAt string
}

type SuccessDurationsSinceRow struct {
	StartedAt  string
	DurationMs sql.NullInt64
}

func (q *Queries) SuccessDurationsSince(ctx context.Context, arg SuccessDurationsSinceParams) ([]SuccessDurationsSinceRow, error) {
	rows, err := q.db.QueryContext(ctx, successDurationsSince, arg.JobID, arg.StartedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SuccessDurationsSinceRow
	for rows.Next() {
		var i SuccessDurationsSinceRow
		if err := rows.Scan(&i.StartedAt, &i.DurationMs); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
