// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: runs.sql

package db

import (
	"context"
	"database/sql"
)

const createRun = `-- name: CreateRun :exec
INSERT INTO runs (id, job_id, started_at, status, created_at)
VALUES (?, ?, ?, 'running', ?)
`

type CreateRunParams struct {
	ID        string
	JobID     string
	StartedAt string
	CreatedAt string
}

func (q *Queries) CreateRun(ctx context.Context, arg CreateRunParams) error {
	_, err := q.db.ExecContext(ctx, createRun,
		arg.ID,
		arg.JobID,
		arg.StartedAt,
		arg.CreatedAt,
	)
	return err
}

const finishRun = `-- name: FinishRun :execrows
UPDATE runs SET ended_at = ?, duration_ms = ?, status = ?, exit_code = ?,
    stdout = ?, stderr = ?, combined_log = ?, truncated = ?
WHERE id = ? AND status = 'running'
`

type FinishRunParams struct {
	EndedAt     sql.NullString
	DurationMs  sql.NullInt64
	Status      string
	ExitCode    sql.NullInt64
	Stdout      string
	Stderr      string
	CombinedLog string
	Truncated   int64
	ID          string
}

func (q *Queries) FinishRun(ctx context.Context, arg FinishRunParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, finishRun,
		arg.EndedAt,
		arg.DurationMs,
		arg.Status,
		arg.ExitCode,
		arg.Stdout,
		arg.Stderr,
		arg.CombinedLog,
		arg.Truncated,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getRun = `-- name: GetRun :one
SELECT id, job_id, started_at, ended_at, duration_ms, status, exit_code, stdout, stderr, combined_log, truncated, created_at FROM runs WHERE id = ?
`

func (q *Queries) GetRun(ctx context.Context, id string) (Run, error) {
	row := q.db.QueryRowContext(ctx, getRun, id)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.StartedAt,
		&i.EndedAt,
		&i.DurationMs,
		&i.Status,
		&i.ExitCode,
		&i.Stdout,
		&i.Stderr,
		&i.CombinedLog,
		&i.Truncated,
		&i.CreatedAt,
	)
	return i, err
}

const listRuns = `-- name: ListRuns :many
SELECT id, job_id, started_at, ended_at, duration_ms, status, exit_code, stdout, stderr, combined_log, truncated, created_at FROM runs ORDER BY started_at DESC LIMIT ?
`

func (q *Queries) ListRuns(ctx context.Context, limit int64) ([]Run, error) {
	rows, err := q.db.QueryContext(ctx, listRuns, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Run
	for rows.Next() {
		var i Run
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.StartedAt,
			&i.EndedAt,
			&i.DurationMs,
			&i.Status,
			&i.ExitCode,
			&i.Stdout,
			&i.Stderr,
			&i.CombinedLog,
			&i.Truncated,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunsForJob = `-- name: ListRunsForJob :many
SELECT id, job_id, started_at, ended_at, duration_ms, status, exit_code, stdout, stderr, combined_log, truncated, created_at FROM runs WHERE job_id = ? ORDER BY started_at DESC LIMIT ?
`

type ListRunsForJobParams struct {
	JobID string
	Limit int64
}

func (q *Queries) ListRunsForJob(ctx context.Context, arg ListRunsForJobParams) ([]Run, error) {
	rows, err := q.db.QueryContext(ctx, listRunsForJob, arg.JobID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Run
	for rows.Next() {
		var i Run
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.StartedAt,
			&i.EndedAt,
			&i.DurationMs,
			&i.Status,
			&i.ExitCode,
			&i.Stdout,
			&i.Stderr,
			&i.CombinedLog,
			&i.Truncated,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
